system:
#Какой таймаут делать между пингами
  sleep_after_check: ${SLEEP_AFTER_CHECK:10s}
#Идентификация пингера
  pinger_ident: ${PINGER_IDENT:PINGER-UKRAINE}
#Конфигурация логгера
  logger:
     console:
        enabled: true
        enable_color: false
        log_level: ${LOG_LEVEL_INT:6}

prometheus:
  path: /metrics
  enabled: true
  port: 2112

#Конфигруция апи
api:
#Адрес получения списка на пинг
  host_list_addr: ${API_HOST_LIST_URL:http://127.0.0.1:9099/api/v1/component/pinger/pinger}
#Адрес отправки изменений
  report_addr: ${API_REPORTS_URL:http://127.0.0.1:9099/api/v1/component/pinger/pinger}
#Таймаут ожидания
  request_timeout: ${API_TIMEOUT:30s}


#Конфигурация библиотеки пингера
pinger:
  #Fast mode
  fast_mode: no
  #Приблизительное количество хостов(устанавливает размер хеша). Нужно брать с небольшим запасом, +1000 например
  approximate_host_quantity: 30000
  #Настройки ICMP проверки
  icmp_check:
    #Количество проходов
    number_of_inspection: 3
    #Количество успешных проходов(хост ответил на пинг нужным количеством пакетов за проход) и считается работающим
    must_inspections_success_for_up: 2
    #Количество неуспешных проходов(хост НЕ ответил на пинг нужным количеством пакетов за проход) и считается упавшим
    must_inspections_failed_for_down: 1
    #Количество воркеров, читающих ответы
    count_listeners: 4
    #Количество воркеров, генерирующие пакеты
    count_writers: 2
    #Работать с IPv6 хостами (будет открыт еще один сокет)
    enable_ipv6: no
    #Ожидание задержавшихся ответов после отправки всех пакетов
    response_timeout: 2s
    #Задержка между проходами
    inspection_timeout: 100ms
    #Количество пакетов на хост при проходе инспекции. Принцип работы аналогичен fping
    #Рекомендуется не изменять данный  параметр, если нет проблем с блокировками за флуд
    count_packages_to_host: 5
    #Рекомендуется не изменять данный  параметр, если нет проблем с блокировками за флуд
    #Необходимое количетво полученных пакетов для учета хоста в обходе как успешного
    must_packages_for_up: 2
    #Рекомендуется не изменять данный  параметр, если нет проблем с блокировками за флуд
    #Время задержки отправки пакета на хост
    time_duration_to_send: 7000ns
  tcp_check:
    #Включена
    enabled: yes
    #Список портов на проверку. Задержка проверки высчитывается по count(ports)*connect_timeout, соответственно 4 порта *3s = 12s ожидания
    ports:
      - 80
    #Количество обработчиков TCP подключений
    count_workers: 50
    #Время ожидания на установку подключения
    connect_timeout: 5s




